// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa6zZiysvP0dXSX03DFNwqmaIBh8w5tuY',
    appId: '1:226397972835:web:217a70ab82b3c9e0798b56',
    messagingSenderId: '226397972835',
    projectId: 'new-1-1b8a7',
    authDomain: 'new-1-1b8a7.firebaseapp.com',
    storageBucket: 'new-1-1b8a7.appspot.com',
    measurementId: 'G-M6BG162SP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY2LELgc6NW-pU8CZnUV4P68zn4ckyLds',
    appId: '1:226397972835:android:4aa4e86f01364f79798b56',
    messagingSenderId: '226397972835',
    projectId: 'new-1-1b8a7',
    storageBucket: 'new-1-1b8a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsqd38a92T3tuRdRo0HuCxJYAostPWU4Q',
    appId: '1:226397972835:ios:273a3695426e560e798b56',
    messagingSenderId: '226397972835',
    projectId: 'new-1-1b8a7',
    storageBucket: 'new-1-1b8a7.appspot.com',
    iosBundleId: 'com.example.nyTimes1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsqd38a92T3tuRdRo0HuCxJYAostPWU4Q',
    appId: '1:226397972835:ios:a95547714cd18db9798b56',
    messagingSenderId: '226397972835',
    projectId: 'new-1-1b8a7',
    storageBucket: 'new-1-1b8a7.appspot.com',
    iosBundleId: 'com.example.nyTimes1.RunnerTests',
  );
}
